import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { SiHtml5, SiCss3, SiJavascript, SiTypescript, SiReact, SiRedux, SiTailwindcss, SiNodedotjs, SiMongodb, SiPostgresql, SiNextdotjs } from "react-icons/si"
import { BsFillMoonStarsFill } from "react-icons/bs";
import { IoLogoWhatsapp } from "react-icons/io";
import { BiLogoGmail } from "react-icons/bi";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import Image from "next/image";
import imageNatureEssence from "../public/naturessence.png";
import imageSpotifyClone from "../public/spotifyclone.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portafolio - Benny Huaman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-5 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbybenny</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              {/* <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-[#3198DA] text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li> */}
            </ul>
          </nav>
          <div className="flex flex-col items-center text-center p-10 py-3">
            <h2 className="text-3xl py-2 text-[#3198DA] font-medium dark:text-[#3198DA] md:text-6xl">
              Benny Huaman
            </h2>
            <h3 className="text-lg py-2 dark:text-white md:text-3xl font-medium">
              Desarrollador Web Full Stack
            </h3>
            <p className="text-md py-3 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Poseo habilidades tanto en el front-end como en el back-end, capaz de crear soluciones eficientes y funcionales.
            </p>
            <div className="text-3xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400 md:text-5xl">
              <a href="https://www.linkedin.com/in/benny-huaman/" target="_blank" rel="noreferrer"><AiFillLinkedin className="hover:text-sky-400 hover:cursor-pointer" /></a>
              <a href="https://github.com/BHuamanCallupe" target="_blank" rel="noreferrer"><AiFillGithub className="hover:text-yellow-300 hover:cursor-pointer" /></a>
              <a href="https://wa.me/987352260/?text=Hola%20Benny.%20Soy..." target="_blank" rel="noreferrer"><IoLogoWhatsapp className="hover:text-green-500 hover:cursor-pointer" /></a>
              <a href="mailto:benny.fhc@gmail.com?body=Hola%20Benny.%20Soy..." target="_blank" rel="noreferrer"><BiLogoGmail className="hover:text-red-500 hover:cursor-pointer" /></a>
            </div>
            <div className="bg-gradient-to-b from-[#3198DA] rounded-full w-80 h-80 relative md:h-96 md:w-96 mt-2">
              <Image src={deved} layout="fill" objectFit="cover" alt="logofoto" className="rounded-full" />
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-lg py-1 dark:text-white mb-5 text-center md:text-3xl">Mis Tecnologías Front-end y Back-end</h3>
            <div className="flex gap-5 flex-wrap justify-center">
              <SiHtml5 className="text-[#e34c26] dark:bg-white p-3 rounded-3xl" size={120} />
              <SiCss3 className="text-[#264de4] dark:bg-white p-3 rounded-3xl" size={120} />
              <SiJavascript className="text-[#F0DB4F] dark:bg-white p-3 rounded-3xl" size={120} />
              <SiTypescript className="text-[#007acc] dark:bg-white p-3 rounded-3xl" size={120} />
              <SiReact className="text-[#61DBFB] dark:bg-white p-3 rounded-3xl" size={120} />
              <SiRedux className="text-[#764abc] dark:bg-white p-3 rounded-3xl" size={120} />
              <SiTailwindcss className="text-[#01B7D6] dark:bg-white p-3 rounded-3xl" size={120} />
              <SiNextdotjs className="dark:bg-white p-3 rounded-3xl" size={120} />
              <SiNodedotjs className="text-[#68A063] dark:bg-white p-3 rounded-3xl" size={120} />
              <SiMongodb className="text-[#4DB33D] dark:bg-white p-3 rounded-3xl" size={120} />
              <SiPostgresql className="text-[#0064a5] dark:bg-white p-3 rounded-3xl" size={120} />
            </div>
          </div>

        </section>
        <section className="py-10">
          <div>
            <h3 className="text-lg py-1 dark:text-white md:text-3xl">Proyectos</h3>
          </div>
          <div className="flex flex-col gap-10 lg:flex-row lg:flex-wrap md:flex-row">
            <div className="basis-1/3 flex-1 ">
              <div className="flex flex-col">
                <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 truncate overflow-hidden">
                  Nature Essence - Tu belleza natural merece productos naturales!
                </p>

                <a href="https://pf-henry-front-ten.vercel.app" target="_blank" rel="noreferrer">
                  <Image
                    className="rounded-lg object-scale-down hover:opacity-100 opacity-80 w-full h-auto"
                    layout="responsive"
                    src={imageNatureEssence}
                    alt="Natur Essence"
                  />
                </a>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="flex flex-col">
                <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 truncate overflow-hidden">
                  App de canciones - Guarda tu cancion favorita!!
                </p>
                <a href="https://spotify-clone-azure-delta.vercel.app/" target="_blank" rel="noreferrer">
                  <Image
                    className="rounded-lg object-scale-down hover:opacity-100 opacity-80 w-full h-auto"
                    layout="responsive"
                    src={imageSpotifyClone}
                    alt="Natur Essence"
                  />
                </a>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
